<?php

use Illuminate\Database\Seeder;

class CommunesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $communes = array(

            ['Arica',1],
            ['Camarones',1],
            ['General Lagos',2],
            ['Putre',2],
            ['Alto Hospicio',3],
            ['Iquique',3],
            ['Camiña',4],
            ['Colchane',4],
            ['Huara',4],
            ['Pica',4],
            ['Pozo Almonte',4],
            ['Tocopilla',5],
            ['María Elena',5],
            ['Calama',6],
            ['Ollague',6],
            ['San Pedro de Atacama',6],
            ['Antofagasta',7],
            ['Mejillones',7],
            ['Sierra Gorda',7],
            ['Taltal',7],
            ['Chañaral',8],
            ['Diego de Almagro',8],
            ['Copiapó',9],
            ['Caldera',9],
            ['Tierra Amarilla',9],
            ['Vallenar',10],
            ['Alto del Carmen',10],
            ['Freirina',10],
            ['Huasco',10],
            ['La Serena',11],
            ['Coquimbo',11],
            ['Andacollo',11],
            ['La Higuera',11],
            ['Paihuano',11],
            ['Vicuña',11],
            ['Ovalle',12],
            ['Combarbalá',12],
            ['Monte Patria',12],
            ['Punitaqui',12],
            ['Río Hurtado',12],
            ['Illapel',13],
            ['Canela',13],
            ['Los Vilos',13],
            ['Salamanca',13],
            ['La Ligua',14],
            ['Cabildo',14],
            ['Zapallar',14],
            ['Papudo',14],
            ['Petorca',14],
            ['Los Andes',15],
            ['San Esteban',15],
            ['Calle Larga',15],
            ['Rinconada',15],
            ['San Felipe',16],
            ['Llaillay',16],
            ['Putaendo',16],
            ['Santa María',16],
            ['Catemu',16],
            ['Panquehue',16],
            ['Quillota',17],
            ['La Cruz',17],
            ['La Calera',17],
            ['Nogales',17],
            ['Hijuelas',17],
            ['Valparaíso',18],	
            ['Viña del Mar',18],
            ['Concón',18],
            ['Quintero',18],
            ['Puchuncaví',18],
            ['Casablanca',18],
            ['Juan Fernández',18],
            ['San Antonio',19],
            ['Cartagena',19],
            ['El Tabo',19],
            ['El Quisco',19],
            ['Algarrobo',19],
            ['Santo Domingo',19],
            ['Isla de Pascua',20],
            ['Quilpué',21],
            ['Limache',21],
            ['Olmué',21],
            ['Villa Alemana',21],
            ['Colina',22],
            ['Lampa',22],
            ['Tiltil',22],
            ['Santiago',23],
            ['Vitacura',23],
            ['San Ramón',23],
            ['San Miguel',23],
            ['San Joaquín',23],
            ['Renca',23],
            ['Recoleta',23],
            ['Quinta Normal',23],
            ['Quilicura',23],
            ['Pudahuel',23],
            ['Providencia',23],
            ['Peñalolén',23],
            ['Pedro Aguirre Cerda',23],
            ['Ñuñoa',23],
            ['Maipú',23],
            ['Macul',23],
            ['Lo Prado',23],
            ['Lo Espejo',23],
            ['Lo Barnechea',23],
            ['Las Condes',23],
            ['La Reina',23],
            ['La Pintana',23],
            ['La Granja',23],
            ['La Florida',23],
            ['La Cisterna',23],
            ['Independencia',23],
            ['Huechuraba',23],
            ['Estación Central',23],
            ['El Bosque',23],
            ['Conchalí',23],
            ['Cerro Navia',23],
            ['Cerrillos',23],
            ['Puente Alto',24],
            ['San José de Maipo',24],
            ['Pirque',24],
            ['San Bernardo',25],
            ['Buin',25],
            ['Paine',25],
            ['Calera de Tango',25],
            ['Melipilla',26],
            ['Alhué',26],
            ['Curacaví',26],
            ['María Pinto',26],
            ['San Pedro',26],
            ['Isla de Maipo',27],
            ['El Monte',27],
            ['Padre Hurtado',27],
            ['Peñaflor',27],
            ['Talagante',27],
            ['Codegua',28],
            ['Coínco',28],
            ['Coltauco',28],
            ['Doñihue',28],
            ['Graneros',28],
            ['Las Cabras',28],
            ['Machalí',28],
            ['Malloa',28],
            ['Mostazal',28],
            ['Olivar',28],
            ['Peumo',28],
            ['Pichidegua',28],
            ['Quinta de Tilcoco',28],
            ['Rancagua',28],
            ['Rengo',28],
            ['Requínoa',28],
            ['San Vicente de Tagua Tagua',28],
            ['Chépica',29],
            ['Chimbarongo',29],
            ['Lolol',29],
            ['Nancagua',29],
            ['Palmilla',29],
            ['Peralillo',29],
            ['Placilla',29],
            ['Pumanque',29],
            ['San Fernando',29],
            ['Santa Cruz',29],
            ['La Estrella',30],
            ['Litueche',30],
            ['Marchigüe',30],
            ['Navidad',30],
            ['Paredones',30],
            ['Pichilemu',30],
            ['Curicó',31],
            ['Hualañé',31],
            ['Licantén',31],
            ['Molina',31],
            ['Rauco',31],
            ['Romeral',31],
            ['Sagrada Familia',31],
            ['Teno',31],
            ['Vichuquén',31],
            ['Talca',32],
            ['San Clemente',32],
            ['Pelarco',32],
            ['Pencahue',32],
            ['Maule',32],
            ['San Rafael',32],
            ['Curepto',33],
            ['Constitución',32],
            ['Empedrado',32],
            ['Río Claro',32],
            ['Linares',33],
            ['San Javier',33],
            ['Parral',33],
            ['Villa Alegre',33],
            ['Longaví',33],
            ['Colbún',33],
            ['Retiro',33],
            ['Yerbas Buenas',33],
            ['Cauquenes',34],
            ['Chanco',34],
            ['Pelluhue',34],
            ['Bulnes',35],
            ['Chillán',35],
            ['Chillán Viejo',35],
            ['El Carmen',35],
            ['Pemuco',35],
            ['Pinto',35],
            ['Quillón',35],
            ['San Ignacio',35],
            ['Yungay',35],
            ['Cobquecura',36],
            ['Coelemu',36],
            ['Ninhue',36],
            ['Portezuelo',36],
            ['Quirihue',36],
            ['Ránquil',36],
            ['Treguaco',36],
            ['San Carlos',37],
            ['Coihueco',37],
            ['San Nicolás',37],
            ['Ñiquén',37],
            ['San Fabián',37],
            ['Alto Biobío',38],
            ['Antuco',38],
            ['Cabrero',38],
            ['Laja',38],
            ['Los Ángeles',38],
            ['Mulchén',38],
            ['Nacimiento',38],
            ['Negrete',38],
            ['Quilaco',38],
            ['Quilleco',38],
            ['San Rosendo',38],
            ['Santa Bárbara',38],
            ['Tucapel',38],
            ['Yumbel',38],
            ['Concepción',39],
            ['Coronel',39],
            ['Chiguayante',39],
            ['Florida',39],
            ['Hualpén',39],
            ['Hualqui',39],
            ['Lota',39],
            ['Penco',39],
            ['San Pedro de La Paz',39],
            ['Santa Juana',39],
            ['Talcahuano',39],
            ['Tomé',39],
            ['Arauco',40],
            ['Cañete',40],
            ['Contulmo',40],
            ['Curanilahue',40],
            ['Lebu',40],
            ['Los Álamos',40],
            ['Tirúa',40],
            ['Angol',41],
            ['Collipulli',41],
            ['Curacautín',41],
            ['Ercilla',41],
            ['Lonquimay',41],
            ['Los Sauces',41],
            ['Lumaco',41],
            ['Purén',41],
            ['Renaico',41],
            ['Traiguén',41],
            ['Victoria',41],
            ['Temuco',42],
            ['Carahue',42],
            ['Cholchol',42],
            ['Cunco',42],
            ['Curarrehue',42],
            ['Freire',42],
            ['Galvarino',42],
            ['Gorbea',42],
            ['Lautaro',42],
            ['Loncoche',42],
            ['Melipeuco',42],
            ['Nueva Imperial',42],
            ['Padre Las Casas',42],
            ['Perquenco',42],
            ['Pitrufquén',42],
            ['Pucón',42],
            ['Saavedra',42],
            ['Teodoro Schmidt',42],
            ['Toltén',42],
            ['Vilcún',42],
            ['Villarrica',42],
            ['Valdivia',43],
            ['Corral',43],
            ['Lanco',43],
            ['Los Lagos',43],
            ['Máfil',43],
            ['Mariquina',43],
            ['Paillaco',43],
            ['Panguipulli',43],
            ['La Unión',44],
            ['Futrono',44],
            ['Lago Ranco',44],
            ['Río Bueno',44],
            ['Osorno',45],
            ['Puerto Octay',45],
            ['Purranque',45],
            ['Puyehue',45],
            ['Río Negro',45],
            ['San Juan de la Costa',45],
            ['San Pablo',45],
            ['Calbuco',46],
            ['Cochamó',46],
            ['Fresia',46],
            ['Frutillar',46],
            ['Llanquihue',46],
            ['Los Muermos',46],
            ['Maullín',46],
            ['Puerto Montt',46],
            ['Puerto Varas',46],
            ['Ancud',47],
            ['Castro',47],
            ['Chonchi',47],
            ['Curaco de Vélez',47],
            ['Dalcahue',47],
            ['Puqueldón',47],
            ['Queilén',47],
            ['Quellón',47],
            ['Quemchi',47],
            ['Quinchao',47],
            ['Chaitén',48],
            ['Futaleufú',48],
            ['Hualaihué',48],
            ['Palena',48],
            ['Lago Verde',49],
            ['Coihaique',49],
            ['Aysén',50],
            ['Cisnes',50],
            ['Guaitecas',50],
            ['Río Ibáñez',51],
            ['Chile Chico',51],
            ['Cochrane',52],
            ['O\'Higgins',52],
            ['Tortel',52],
            ['Natales',53],
            ['Torres del Paine',53],
            ['Laguna Blanca',54],
            ['Punta Arenas',54],
            ['Río Verde',54],
            ['San Gregorio',54],
            ['Porvenir',55],
            ['Primavera',55],
            ['Timaukel',55],
            ['Cabo de Hornos',56],
            ['Antártica',56]
            
            // ['Arica',1],
            // ['Camarones',1],
            // ['General Lagos',2],
            // ['Putre',2],
            // ['Alto Hospicio',3],
            // ['Iquique',3],
            // ['Camiña',4],
            // ['Colchane',4],
            // ['Huara',4],
            // ['Pica',4],
            // ['Pozo Almonte',4],
            // ['Antofagasta',5],
            // ['Mejillones',5],
            // ['Sierra Gorda',5],
            // ['Taltal',5],
            // ['Calama',6],
            // ['Ollague',6],
            // ['San Pedro de Atacama',6],
            // ['María Elena',7],
            // ['Tocopilla',7],
            // ['Chañaral',8],
            // ['Diego de Almagro',8],
            // ['Caldera',9],
            // ['Copiapó',9],
            // ['Tierra Amarilla',9],
            // ['Alto del Carmen',10],
            // ['Freirina',10],
            // ['Huasco',10],
            // ['Vallenar',10],
            // ['Canela',11],
            // ['Illapel',11],
            // ['Los Vilos',11],
            // ['Salamanca',11],
            // ['Andacollo',12],
            // ['Coquimbo',12],
            // ['La Higuera',12],
            // ['La Serena',12],
            // ['Paihuaco',12],
            // ['Vicuña',12],
            // ['Combarbalá',13],
            // ['Monte Patria',13],
            // ['Ovalle',13],
            // ['Punitaqui',13],
            // ['Río Hurtado',13],
            // ['Isla de Pascua',14],
            // ['Calle Larga',15],
            // ['Los Andes',15],
            // ['Rinconada',15],
            // ['San Esteban',15],
            // ['La Ligua',16],
            // ['Papudo',16],
            // ['Petorca',16],
            // ['Zapallar',16],
            // ['Hijuelas',17],
            // ['La Calera',17],
            // ['La Cruz',17],
            // ['Limache',17],
            // ['Nogales',17],
            // ['Olmué',17],
            // ['Quillota',17],
            // ['Algarrobo',18],
            // ['Cartagena',18],
            // ['El Quisco',18],
            // ['El Tabo',18],
            // ['San Antonio',18],
            // ['Santo Domingo',18],
            // ['Catemu',19],
            // ['Llaillay',19],
            // ['Panquehue',19],
            // ['Putaendo',19],
            // ['San Felipe',19],
            // ['Santa María',19],
            // ['Casablanca',20],
            // ['Concón',20],
            // ['Juan Fernández',20],
            // ['Puchuncaví',20],
            // ['Quilpué',20],
            // ['Quintero',20],
            // ['Valparaíso',20],
            // ['Villa Alemana',20],
            // ['Viña del Mar',20],
            // ['Colina',21],
            // ['Lampa',21],
            // ['Tiltil',21],
            // ['Pirque',22],
            // ['Puente Alto',22],
            // ['San José de Maipo',22],
            // ['Buin',23],
            // ['Calera de Tango',23],
            // ['Paine',23],
            // ['San Bernardo',23],
            // ['Alhué',24],
            // ['Curacaví',24],
            // ['María Pinto',24],
            // ['Melipilla',24],
            // ['San Pedro',24],
            // ['Cerrillos',25],
            // ['Cerro Navia',25],
            // ['Conchalí',25],
            // ['El Bosque',25],
            // ['Estación Central',25],
            // ['Huechuraba',25],
            // ['Independencia',25],
            // ['La Cisterna',25],
            // ['La Granja',25],
            // ['La Florida',25],
            // ['La Pintana',25],
            // ['La Reina',25],
            // ['Las Condes',25],
            // ['Lo Barnechea',25],
            // ['Lo Espejo',25],
            // ['Lo Prado',25],
            // ['Macul',25],
            // ['Maipú',25],
            // ['Ñuñoa',25],
            // ['Pedro Aguirre Cerda',25],
            // ['Peñalolén',25],
            // ['Providencia',25],
            // ['Pudahuel',25],
            // ['Quilicura',25],
            // ['Quinta Normal',25],
            // ['Recoleta',25],
            // ['Renca',25],
            // ['San Miguel',25],
            // ['San Joaquín',25],
            // ['San Ramón',25],
            // ['Santiago',25],
            // ['Vitacura',25],
            // ['El Monte',26],
            // ['Isla de Maipo',26],
            // ['Padre Hurtado',26],
            // ['Peñaflor',26],
            // ['Talagante',26],
            // ['Codegua',27],
            // ['Coínco',27],
            // ['Coltauco',27],
            // ['Doñihue',27],
            // ['Graneros',27],
            // ['Las Cabras',27],
            // ['Machalí',27],
            // ['Malloa',27],
            // ['Mostazal',27],
            // ['Olivar',27],
            // ['Peumo',27],
            // ['Pichidegua',27],
            // ['Quinta de Tilcoco',27],
            // ['Rancagua',27],
            // ['Rengo',27],
            // ['Requínoa',27],
            // ['San Vicente de Tagua Tagua',27],
            // ['La Estrella',28],
            // ['Litueche',28],
            // ['Marchihue',28],
            // ['Navidad',28],
            // ['Peredones',28],
            // ['Pichilemu',28],
            // ['Chépica',29],
            // ['Chimbarongo',29],
            // ['Lolol',29],
            // ['Nancagua',29],
            // ['Palmilla',29],
            // ['Peralillo',29],
            // ['Placilla',29],
            // ['Pumanque',29],
            // ['San Fernando',29],
            // ['Santa Cruz',29],
            // ['Cauquenes',30],
            // ['Chanco',30],
            // ['Pelluhue',30],
            // ['Curicó',31],
            // ['Hualañé',31],
            // ['Licantén',31],
            // ['Molina',31],
            // ['Rauco',31],
            // ['Romeral',31],
            // ['Sagrada Familia',31],
            // ['Teno',31],
            // ['Vichuquén',31],
            // ['Colbún',32],
            // ['Linares',32],
            // ['Longaví',32],
            // ['Parral',32],
            // ['Retiro',32],
            // ['San Javier',32],
            // ['Villa Alegre',32],
            // ['Yerbas Buenas',32],
            // ['Constitución',33],
            // ['Curepto',33],
            // ['Empedrado',33],
            // ['Maule',33],
            // ['Pelarco',33],
            // ['Pencahue',33],
            // ['Río Claro',33],
            // ['San Clemente',33],
            // ['San Rafael',33],
            // ['Talca',33],
            // ['Arauco',34],
            // ['Cañete',34],
            // ['Contulmo',34],
            // ['Curanilahue',34],
            // ['Lebu',34],
            // ['Los Álamos',34],
            // ['Tirúa',34],
            // ['Alto Biobío',35],
            // ['Antuco',35],
            // ['Cabrero',35],
            // ['Laja',35],
            // ['Los Ángeles',35],
            // ['Mulchén',35],
            // ['Nacimiento',35],
            // ['Negrete',35],
            // ['Quilaco',35],
            // ['Quilleco',35],
            // ['San Rosendo',35],
            // ['Santa Bárbara',35],
            // ['Tucapel',35],
            // ['Yumbel',35],
            // ['Chiguayante',36],
            // ['Concepción',36],
            // ['Coronel',36],
            // ['Florida',36],
            // ['Hualpén',36],
            // ['Hualqui',36],
            // ['Lota',36],
            // ['Penco',36],
            // ['San Pedro de La Paz',36],
            // ['Santa Juana',36],
            // ['Talcahuano',36],
            // ['Tomé',36],
            // ['Bulnes',37],
            // ['Chillán',37],
            // ['Chillán Viejo',37],
            // ['Cobquecura',37],
            // ['Coelemu',37],
            // ['Coihueco',37],
            // ['El Carmen',37],
            // ['Ninhue',37],
            // ['Ñiquen',37],
            // ['Pemuco',37],
            // ['Pinto',37],
            // ['Portezuelo',37],
            // ['Quillón',37],
            // ['Quirihue',37],
            // ['Ránquil',37],
            // ['San Carlos',37],
            // ['San Fabián',37],
            // ['San Ignacio',37],
            // ['San Nicolás',37],
            // ['Treguaco',37],
            // ['Yungay',37],
            // ['Carahue',38],
            // ['Cholchol',38],
            // ['Cunco',38],
            // ['Curarrehue',38],
            // ['Freire',38],
            // ['Galvarino',38],
            // ['Gorbea',38],
            // ['Lautaro',38],
            // ['Loncoche',38],
            // ['Melipeuco',38],
            // ['Nueva Imperial',38],
            // ['Padre Las Casas',38],
            // ['Perquenco',38],
            // ['Pitrufquén',38],
            // ['Pucón',38],
            // ['Saavedra',38],
            // ['Temuco',38],
            // ['Teodoro Schmidt',38],
            // ['Toltén',38],
            // ['Vilcún',38],
            // ['Villarrica',38],
            // ['Angol',39],
            // ['Collipulli',39],
            // ['Curacautín',39],
            // ['Ercilla',39],
            // ['Lonquimay',39],
            // ['Los Sauces',39],
            // ['Lumaco',39],
            // ['Purén',39],
            // ['Renaico',39],
            // ['Traiguén',39],
            // ['Victoria',39],
            // ['Corral',40],
            // ['Lanco',40],
            // ['Los Lagos',40],
            // ['Máfil',40],
            // ['Mariquina',40],
            // ['Paillaco',40],
            // ['Panguipulli',40],
            // ['Valdivia',40],
            // ['Futrono',41],
            // ['La Unión',41],
            // ['Lago Ranco',41],
            // ['Río Bueno',41],
            // ['Ancud',42],
            // ['Castro',42],
            // ['Chonchi',42],
            // ['Curaco de Vélez',42],
            // ['Dalcahue',42],
            // ['Puqueldón',42],
            // ['Queilén',42],
            // ['Quemchi',42],
            // ['Quellón',42],
            // ['Quinchao',42],
            // ['Calbuco',43],
            // ['Cochamó',43],
            // ['Fresia',43],
            // ['Frutillar',43],
            // ['Llanquihue',43],
            // ['Los Muermos',43],
            // ['Maullín',43],
            // ['Puerto Montt',43],
            // ['Puerto Varas',43],
            // ['Osorno',44],
            // ['Puero Octay',44],
            // ['Purranque',44],
            // ['Puyehue',44],
            // ['Río Negro',44],
            // ['San Juan de la Costa',44],
            // ['San Pablo',44],
            // ['Chaitén',45],
            // ['Futaleufú',45],
            // ['Hualaihué',45],
            // ['Palena',45],
            // ['Aisén',46],
            // ['Cisnes',46],
            // ['Guaitecas',46],
            // ['Cochrane',47],
            // ['O\'higgins',47],
            // ['Tortel',47],
            // ['Coihaique',48],
            // ['Lago Verde',48],
            // ['Chile Chico',49],
            // ['Río Ibáñez',49],
            // ['Antártica',50],
            // ['Cabo de Hornos',50],
            // ['Laguna Blanca',51],
            // ['Punta Arenas',51],
            // ['Río Verde',51],
            // ['San Gregorio',51],
            // ['Porvenir',52],
            // ['Primavera',52],
            // ['Timaukel',52],
            // ['Natales',53],
            // ['Torres del Paine',53],
        );

        foreach ($communes as $commune) {
            DB::table('communes')->insert([
                'name' => $commune[0],
                'province_id' => $commune[1],
            ]); 
        }
    }
}
