<?php

use Illuminate\Database\Seeder;

class SalariesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $salaries = array(
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 1,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 2,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 3,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 15000, 
                'health_pay'   =>  0,
                'heavy_duty_work_pay' => 50000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 4,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 5,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 6,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 7,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 8,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 9,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 10,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 11,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 19, 
                'month' => 12,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],

            
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 1,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 2,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 3,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 15000, 
                'health_pay'   =>  0,
                'heavy_duty_work_pay' => 50000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 4,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 5,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 6,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 7,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 8,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 9,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 10,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 11,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 19, 
                'month' => 12,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],



            
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 1,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 2,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 3,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 15000, 
                'health_pay'   =>  0,
                'heavy_duty_work_pay' => 50000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 4,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 5,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 6,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 7,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 8,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 9,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 10,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 11,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 5,
                'year' => 20, 
                'month' => 12,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],

            
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 1,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 2,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 3,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 15000, 
                'health_pay'   =>  0,
                'heavy_duty_work_pay' => 50000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 4,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 5,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 6,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 7,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 8,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 9,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 10,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 11,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            [
                'worker_id' => 6,
                'year' => 20, 
                'month' => 12,
                'total_earnings' => 350000,
                'accident_insurance' => 50000,
                'severance_pay' => 25000, 
                'health_pay'   =>  75000,
                'heavy_duty_work_pay' => 100000, 
            ],
            
        );
        
        foreach ($salaries as $salary) {
            DB::table('salaries')->insert([
                'worker_id' => $salary['worker_id'],
                'year' => $salary['year'],
                'month' => $salary['month'],
                'total_earnings' => $salary['total_earnings'],
                'accident_insurance' => $salary['accident_insurance'],
                'severance_pay' => $salary['severance_pay'],
                'health_pay' => $salary['health_pay'],
                'heavy_duty_work_pay' => $salary['heavy_duty_work_pay'],
                'total' => $salary['total_earnings'] + $salary['accident_insurance'] + $salary['severance_pay'] + $salary['health_pay'] + $salary['heavy_duty_work_pay'],
            ]);        
        }

    }
}
